### ISSUE TITLE
Comments?

### ISSUE THREAD

**Issue by AHumanIBelieve** [geno7/NeoComix#4]
Is there a way to do comments that are consistent for each page. I kinda understand the theory(hold comments in page metadata, use a js function to write it, but I have no clue how to code it(don't know js). Thanks for any help!

**Comment by niborus** [comment]
Hi there, I'm not the original maintainer, but I hope I can help nonetheless. I assume you mean comments where your audience can comment on a page and not the comment of the author (aka, the authors note).

Unfortunately, this is not possible with Rarebit alone. The way Rarebit works, you upload your site and your content to the server and your audience can read this site. This also holds for the JS functions: You upload the JS functions to your server, your audience (or their Web-Browser, to be precise) will download them and then run them on their device.

This means that Rarebit does not run any code on your server and also that your audience can only ever read from the server and not write to it. Since writing to a server is necessary for commenting, they can not post comment via Rarebit.

There are however other ways to have comments. There are a lot of third-party-services which will store and display the comments for you. In this case, the commenter would write to the server of the third-party-service, not to your server. The comments and the comment form would then be embedded into your site by that third-party-service.

These services are not free, but they might not be expensive if you don’t expect thousands of pageviews each day. Search for “embed comments on site” and you should find a dozen different services.

**Comment by AHumanIBelieve** [comment]
Thanks for replying! However, in the end I did end up using a third party supplier (can't remember what it was off the top of my head), before migrating to a different hosting platform altogether. Sorry for forgetting to close the issue, but thanks for the help. AHumanIBelieve
